spring.application.name=TransactionSorter

#run data.sql and schema.sql in src/main/resources folder
spring.sql.init.mode = always

#if u put ./ H2 can create the folder
spring.datasource.url=jdbc:h2:file:./data/notesdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Change depending on if u want to keep or drop database everytime, use UPDATE/none/create-drop
spring.jpa.hibernate.ddl-auto=create-drop

#Enable h2 console
spring.h2.console.enabled=true


#Enable SQL
spring.jpa.show-sql=false